#!/usr/bin/env python

import robot_upstart
import os

j = robot_upstart.Job(name="scalevo-core", interface=os.environ.get('ROBOT_NETWORK'), workspace_setup=os.environ.get('ROBOT_SETUP'))

# Stuff to launch on system startup.
j.add(package="scalevo_bringup", glob="launch/*")

#if os.path.exists('/dev/clearpath/imu'):
#  j.add(package="husky_bringup", glob="launch/um6_config/*")

j.install()
